#!/bin/bash

TARGET=$(zenity --file-selection --title='Selecciona video...')

if [ ! ${#TARGET} -eq 0 ]
then
	DISPLAY_SIZE=$(zenity --list --title="Size Video" \
	--text="Choose size video" \
	--column="value" --column="Size" --hide-column=1 \
	"0 0 0 0" "Full" \
	"0 0 1280 720" "1280x720" \
	"0 0 854 480" "854x480" \
	"0 0 640 360" "640x360")

	if [ ! ${#DISPLAY_SIZE} -eq 0 ]
	then
		omxplayer -o hdmi --win "${DISPLAY_SIZE}" "${TARGET}"
	fi
fi
